name = "diurnus"
license = "MIT"
licenselink = "https://github.com/quowtf/diurnus/blob/master/LICENSE"
description = "My private theme for hugo."
homepage = "https://github.com/quowtf"
tags = ["blog", "minimal", "dark", "responsive"]
features = [
  "single column",
  "social icons",
]
min_version = 0.43

[author]
  name = "quowtf"
  homepage = "https://quo.wtf"
