name = "Diurnus"
license = "MIT"
version = 1.0.0
licenselink = "https://github.com/quowtf/diurnus/blob/master/LICENSE"
description = "A simple, minimal, readable, Hugo theme, or almost."
homepage = "https://github.com/quowtf/diurnus"
tags = ["blog", "minimal", "responsive"]
features = [
  "social icons",
]
min_version = "0.41.0"

[author]
  name = "quowtf"
  homepage = "https://quo.wtf"
